CREATE ROLE "${POSTGRES_KC_USER}" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '${POSTGRES_KC_PASSWORD}';
CREATE DATABASE keycloak OWNER "${POSTGRES_KC_USER}" ENCODING 'utf-8';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO "${POSTGRES_KC_USER}";
GRANT ALL PRIVILEGES ON SCHEMA public TO "${POSTGRES_KC_USER}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${POSTGRES_KC_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${POSTGRES_KC_USER}";
